#!/bin/bash

#code injector

printf "
                                  █████ ████
                                 ░░███ ░░███
 ████████    ██████   ██████   ███████  ░███   ██████
░░███░░███  ███░░███ ███░░███ ███░░███  ░███  ███░░███
 ░███ ░███ ░███████ ░███████ ░███ ░███  ░███ ░███████
 ░███ ░███ ░███░░░  ░███░░░  ░███ ░███  ░███ ░███░░░
 ████ █████░░██████ ░░██████ ░░████████ █████░░██████
░░░░ ░░░░░  ░░░░░░   ░░░░░░   ░░░░░░░░ ░░░░░  ░░░░░░\n"




file_with_code="$2"
Inject_me_Daddy_owo="$3"
extra2="$4"

case $1 in
  -h|help|-help|--help|--h)
  echo "
  needle {option}
  needle replace \"1\" \"2\" {file}
  needle inject 1.txt 2.txt {option}
  needle inject 1.txt 2.txt replace "1" "2" "
  ;;
esac

case $1 in
  replace)
  printf "Replace\n"
  printf "Word-1: $2\n"
  printf "Word-2: $3\n"
  printf "The following keyword ($2) will be Replaced with ($3) in file ($4)\n"
  sed -i "s/$2/$3/g" $4
  ;;
esac

case $1 in
inject)
  printf "Option 1\n"
  printf "File-1: [$file_with_code]\n"
  printf "File-2: [$Inject_me_Daddy_owo]\n"
  if [[ -f "$file_with_code" ]];
  then
    printf "File-1 found!\n"
  else
    echo "File-1 Not found!"
    exit 0
  fi

  if [[ -f "$Inject_me_Daddy_owo" ]];
  then
    printf "File-2 found!\n"
  else
    echo "File-2 Not found!"
    exit 0
  fi
  sleep 1
  printf "Running Injection..."
  cat $file_with_code >> $Inject_me_Daddy_owo
  echo "[*]"
  echo "Done!"
  ;;
esac

case $4 in
  replace)
  printf "Replace\n"
  printf "Word-1: $5\n"
  printf "Word-2: $6\n"
  printf "The following keyword ($5) will be Replaced with ($6) in file ($Inject_me_Daddy_owo)\n"
  sed -i "s/$5/$6/g" $Inject_me_Daddy_owo
  ;;
esac
