#!/bin/bash

#code injector

printf "
                                  █████ ████
                                 ░░███ ░░███
 ████████    ██████   ██████   ███████  ░███   ██████
░░███░░███  ███░░███ ███░░███ ███░░███  ░███  ███░░███
 ░███ ░███ ░███████ ░███████ ░███ ░███  ░███ ░███████
 ░███ ░███ ░███░░░  ░███░░░  ░███ ░███  ░███ ░███░░░
 ████ █████░░██████ ░░██████ ░░████████ █████░░██████
░░░░ ░░░░░  ░░░░░░   ░░░░░░   ░░░░░░░░ ░░░░░  ░░░░░░\n"




#Varible name is nice
file_with_code="$2"
Target="$3"



if [[ -z $1 ]];
then
	echo "Usage:"
	echo "
  needle {option}
  needle replace \"1\" \"2\" {file}
  needle inject 1.txt 2.txt {option}
  needle inject 1.txt 2.txt replace \"1\" \"2\" "
fi

case $1 in
  -h|help|-help|--help|--h)
	echo "Usage:"
  echo "
  needle {option}
  needle replace \"1\" \"2\" {file}
  needle inject 1.txt 2.txt {option}
  needle inject 1.txt 2.txt replace \"1\" \"2\" "
  ;;
esac

case $1 in
  replace)
  printf "Replace\n"
  printf '%s' "Word-1: $2\n"
  printf '%s' "Word-2: $3\n"
  printf '%s' "The following keyword ($2) will be Replaced with ($3) in file ($4)\n"
  sed -i "s/$2/$3/g" "$4"
  ;;
esac

case $1 in
inject)
  printf "Option 1\n"
  printf '%s' "File-1: [$file_with_code]\n"
  printf '%s' "File-2: [$Target]\n"
  if [[ -f "$file_with_code" ]];
  then
    printf "File-1 found!\n"
  else
    echo "File-1 Not found!"
    exit 1
  fi

  if [[ -f "$Target" ]];
  then
    printf "File-2 found!\n"
  else
    echo "File-2 Not found!"
    exit 1
  fi
  sleep 1
  printf "Running Injection..."
  echo '' > "$Target"
  cat "$file_with_code" >> "$Target"
  echo "[*]"
  echo "Done!"
  ;;
esac

#Varible name is nice
case $4 in
  replace)
  printf "Replace\n"
  printf '%s' "Word-1: $5\n"
  printf '%s' "Word-2: $6\n"
  printf '%s' "The following keyword ($5) will be Replaced with ($6) in file ($Target)\n"
  sed -i "s/$5/$6/g" "$Target"
  ;;
esac
